### ISSUE TITLE
Read the repo info and do the installation guide of the library MMOCR [2]

### ISSUE THREAD

**Issue by AgustindelaVega** [Leviatan-Analytics/LA-data-processing#11]
### Time
- Estimated time: 2
- Dedicated time:

**Comment by BraianBGit** [comment]
### Time
- Estimated time: 2
- Dedicated time: 3

**Comment by AgustindelaVega** [comment]
### Time
- Estimated time: 2
- Dedicated time: 3

**Comment by Nestiii** [comment]
Time
- Estimated time: 2
- Dedicated time: 3
