### ISSUE TITLE
Discuss new interface ideas with the LOL analyst [1]

### ISSUE THREAD

**Issue by BraianBGit** [Leviatan-Analytics/LA-data-processing#112]
Have a meeting with the LOL analyst and show him the ideas for the new feature (manual data input for tournament matches).

**Comment by BraianBGit** [comment]
Dedicated time: 1hs

**Comment by AgustindelaVega** [comment]
Dedicated time: 1hs

**Comment by NumaLeone** [comment]
Dedicated time: 1hs
