### ISSUE TITLE
Research text recognition libraries [2]

### ISSUE THREAD

**Issue by Nestiii** [Leviatan-Analytics/LA-data-processing#33]
Estimated time: 2 hs per assignee

* Find libraries with this requirements:
  * AMD and CPU only compatible
  * Windows compatible
  * CUDA compatible (Optional)
* Analyze and compare the libraries found

Output:

* Research Document with the info and comparison of the libraries found

**Comment by BraianBGit** [comment]
Dedicated time: 2 hours

**Comment by Nestiii** [comment]
Dedicated time: 1 h
