### ISSUE TITLE
Research object recognition libraries [2]

### ISSUE THREAD

**Issue by Nestiii** [Leviatan-Analytics/LA-data-processing#38]
Estimated time: 2 hs per assignee

Objectives:

* Find libraries with this requirements:
  * AMD and CPU only compatible
  * Windows compatible
  * CUDA compatible (Optional)
* Analyze and compare the libraries found

Output:

* Research Document with the info and comparison of the libraries found

**Comment by BraianBGit** [comment]
Dedicated time: 2hs

**Comment by Nestiii** [comment]
Dedicated time: 3hs
