### ISSUE TITLE
Sprint retrospective [1]

### ISSUE THREAD

**Issue by Nestiii** [Leviatan-Analytics/LA-data-processing#46]
Estimated time: 1 hs per assignee

Objectives:

- Show client the sprint Progress

**Comment by BraianBGit** [comment]
Dedicated time: 1hs

**Comment by AgustindelaVega** [comment]
Dedicated time: 1h

**Comment by matiasferron** [comment]
dedicated time: 1h

**Comment by Nestiii** [comment]
Dedicated time: 1h

**Comment by NumaLeone** [comment]
Dedicated time: 1h
