### ISSUE TITLE
Redo Sprint Planning [1]

### ISSUE THREAD

**Issue by AgustindelaVega** [Leviatan-Analytics/LA-data-processing#7]
### Time
- Estimated time: 1
- Dedicated time:

**Comment by AgustindelaVega** [comment]
### Time
- Estimated time: 1
- Dedicated time: 1

**Comment by matiasferron** [comment]
Time

    Estimated time: 1
    Dedicated time: 1

**Comment by matiasferron** [comment]
### Time
- Estimated time: 1
- Dedicated time: 1

**Comment by NumaLeone** [comment]
Time
- Estimated time: 1
- Dedicated time: 1

**Comment by Nestiii** [comment]
Time
- Estimated time: 1
- Dedicated time: 1
